### ISSUE TITLE
"You are not allowed"

### ISSUE THREAD

**Issue by gerroon** [genonbeta/TrebleShot#1]
Hi

When I share a file to TS (like a file commander) it says this file cant be sent you are not allowed. 

I like the ability to share content from other apps to this app but this kind of sucks not sure what the problem is. I was trying to send a .pls playlist file.

thanks

**Comment by velitasali** [comment]
Hello :) It's an security feature of the application. When you try to send files from a new device (which doesn't appear on the device that you're sending files to), TrebleShot offers two option "Accept" or "Block". When you click "Block", next requests coming from that device will be rejected.

Fixing it: 

![screenshot_20170528-214100](https://cloud.githubusercontent.com/assets/10258162/26531331/9d1026d8-43ef-11e7-8c21-63ef0614ec14.png)
Simply enable "Allow to access" option whenever it happens :)

**Comment by gerroon** [comment]
Hi

If so then the devices are forgetting the permissions. Because I already gave permission to the device but now I reopened the device setting and allow access is disabled again.

**Comment by velitasali** [comment]
Hello :) When a request is pending in notifications until it is responded by the user, requests are temporarily held by TrebleShot to prevent flooding and if the user forces close the application (possibly by removing from recent app list [Android 6+]),  the app never gets the chance to turn it back. If the problem persists please let me know :)

 Güzel yorumun için teşekkürler :)
