### ISSUE TITLE
French support

### ISSUE THREAD

**Issue by boydkelly** [genonbeta/TrebleShot#10]
Hi,

Awesome app!

I would like to contribute French support.  Can you point me to what file I should create/translate?

Regards,

Boyd

**Comment by velitasali** [comment]
Hi. You can create a folder named values-fr in [here](https://github.com/genonbeta/TrebleShot/tree/master/app/src/main/res) and copy values/strings.xml file to values-fr folder and after that you can make your changes 

Thank you, looking forward to your contribution :)

**Comment by velitasali** [comment]
Hey, TrebleShot is now being translated on https://hosted.weblate.org/engage/TrebleShot/
