### ISSUE TITLE
Is my data secure "on the wire"?

### ISSUE THREAD

**Issue by geebotron** [genonbeta/TrebleShot#11]
Hi - Is the data transmission across the network in a plain format? I.e. un-encrypted?
Would I need to encrypt a file before sending to keep data secure?

Thanks

**Comment by velitasali** [comment]
No, files are not currently encrypted. To keep your data secure you should use private or trusted networks. Encrypting data is a good idea by the way. I will try to include that feature in the next version. Thanks.

**Comment by geebotron** [comment]
Hi Veli,
Thanks for the information. It might be an idea to make it clear (pardon
the pun) that encryption isn't used, in case someone is on an un-trusted
network and doesn't realize.
I like the app by the way - it's useful!

Cheers,

Guy
