### ISSUE TITLE
Trebleshot on android doesn't find any Windows devices running trebleshot

### ISSUE THREAD

**Issue by aha999** [genonbeta/TrebleShot#112]
**Describe the bug**
Trebleshot on Android doesn't find any devices in the same network, i have Trebleshot Desktop on PC.

**Expected behavior**
Trebleshot should find a Windows pc device that is running Trebleshot Desktop, but it does not find it.

**Environment (please complete the following information):**
 - Android version: Android 9 (LineageOS 16)
 - App version Latest continuous build, https://travis-ci.org/genonbeta/TrebleShot/builds/645882335/
 - Device Model and Brand Lenovo P2

**Comment by velitasali** [comment]
This issue is valid but related to the desktop version and can be tracked at 
https://github.com/genonbeta/TrebleShot-Desktop/issues/24.
