### ISSUE TITLE
Hotspot/wifi-direct

### ISSUE THREAD

**Issue by gvlfm78** [genonbeta/TrebleShot#14]
Unless I missed it somewhere in the app there isn't a function to automatically create a hotspot or use Wi-Fi direct to send files to another device, you have to be on the same network already.

This would be extremely useful in making transferring just a couple files to another device quickly, by, for example, scanning a QR code with the information to connect to the access point / Wi-Fi direct.

**Comment by velitasali** [comment]
Yes I know as I recently tried to implement somehing like that. The problem that occurred was that there wasn't an API for hotspot implementation. It requires a hack which I can't really rely on. On the WiFi Direct side I have only one device with a working WiFi Direct feature so even if I add it, I can't test it. However, I'm still open to this kind of feature.

**Comment by gvlfm78** [comment]
Hmm if I recall correctly WiFi direct is backwards compatible with other devices, as in, the other device just sees a hotspot and connects to it.
Either way I'm available to perform some testing with multiple WiFi Direct enabled devices if you get round to implementing this.

**Comment by velitasali** [comment]
Then I will get in touch with you after I prepare the basics and we can schedule a time. Thanks.

**Comment by DMSalesman** [comment]
A bit late, but I was able to open a Wi-Fi hotspot on a device running LineageOS 14.1, make another device join and exchange files effortlessly.

**Comment by velitasali** [comment]
@DMSalesman Well, TrebleShot doesn't need to start its own connection in order to work if this was what you meant.

**Comment by gvlfm78** [comment]
@DMSalesman But the hotspot is not created automatically by the app and you have to connect to it manually for it to work

**Comment by velitasali** [comment]
Hi, hotspot management feature will be present in the next release. Hang tight.

**Comment by gvlfm78** [comment]
Does that mean that TrebleShot creates its own hotspot and the other phone connects to it automatically (QR code perhaps) or do you still connect to it manually?

**Comment by velitasali** [comment]
You will be able to see the networks created by TrebleShot and send files directly by tapping them.

**Comment by gvlfm78** [comment]
Would that be because the hotspots follow a certain naming scheme?

**Comment by velitasali** [comment]
@gvlfm78 Yes, it is. I thought of using QR code method first, but this way seemed to be faster.

**Comment by gvlfm78** [comment]
Alright, although I think for the WiFi direct feature the QR code may be necessary. But this is already an extremely useful feature and I can't wait to try it out.

**Comment by velitasali** [comment]
Duplicate of #81
