### ISSUE TITLE
How does it work ?

### ISSUE THREAD

**Issue by airednot** [genonbeta/TrebleShot#15]
While both (or more) devices are connected to the same router one can share data between devices, please kindly explain few of my questions:

1) By using main router with internet access (where 10+ people are connected to it) and sending 1GB of data between devices using this app, do I impact/overload connection speed for others. Making their internet connection slower ?

2) Can I use it on access point/ repeater that's connected to main router, do I overload network capacity ?

3) Can I use it through Bluetooth ?

4) Can I make direct connection between devices ?

**Comment by velitasali** [comment]
Although it might require a benchmark to be able to answer your first question correctly, I can assume that it will only affect the ping times and unlike downloading files, it will not reduce the download speed available as it doesn't connect a remote server through your internet connection

For the second question, using access point will be faster than using repeater in terms of ping times as a repeater just mirrors the connection of an access point.

Using Bluetooth tethering is a much slower than any other connection. I would only recommend using it for sharing text

You can connect your devices using these types of connections that are possibly present and supported by your devices;
WiFi Hotspot + WiFi client connected to it
WiFi Direct + WiFi Direct 
Bluetooth Tethering + Bluetooth Client connected to it

Although my replies are possible answers for your questions, I can say that most the time it just depends on available environment.

**Comment by airednot** [comment]
Hello again, Thank you for quick answers.

Short story.
Recently my friend wanted to send me a pdf file. And he asked me if I had shareit. I looked at him with surprise because I didn't know what it was. My Bluetooth didn't work so he sent it to me by e-mail later on.

Few days later I researched about that app but after reading about origin and philosophy I decided to look for something more FOSS-like.

In first 1) case scenario I am not able to test it for now. Second 2) pairs but it's very slow (I was testing it on 300mb file), and it dropped transfer after few minutes. Third 3) It didn't work for me (but Bluetooth is slow anyway, so I didn't mind). Fourth 4) with "WiFi Hotspot + WiFi client connected to it" will only (I assume) work with mobile data and I don't have SIM in my phone. On the other hand option with "WiFi Direct + WiFi Direct" WORKED BEAUTIFULLY! with speed up to 5MB/s. 300mb file was transferred within 20 seconds.

I like your app already and will recommend it to everyone who use SI as a must have replacement.

Quick guide for those of you that don't know how to set it up immediately.

1) Download app (of course)
2) Turn your Wi-Fi on
3) go to Settings / WiFi / 3 dots-upper right corner / Advanced / Wi-Fi Direct
4) Do the same in second device
5) You'll see list of devices under "Peer devices", click on it
6) Go to your file browser app, select file and use share it with TrebleShot
7) Select "Other's Device Name"
8) Click on Wi-Fi Direct

Enjoy great app.

One more question. In case of power outage, where there's no Wi-Fi to connect to and no SIM cards present in phones. Is there any way to make it work ?

**Comment by velitasali** [comment]
Actually a SIM-card is never required while using TrebleShot, but Samsung and maybe a few manufacturers sometimes do not allow the usage of Wi-Fi tethering and if I am guessing right, this is also what happened in your case and Wi-Fi direct should always be available whether SIM-card is inserted or not. 

Thanks for your interest in and support for open source. If you just discovered open-source, I can suggest you use F-droid which is full of app like this. Enjoy :)

**Comment by gvlfm78** [comment]
> Turn your Wi-Fi on
go to Settings / WiFi / 3 dots-upper right corner / Advanced / Wi-Fi Direct
Do the same in second device
You'll see list of devices under "Peer devices", click on it

This is why I think allowing two devices with this app to automatically connect using Wi-Fi direct (#14 ) would be great, because it would make transferring a file to someone else a really quick operation.

It would also make this app a serious contender amongst the currently popular file sharing apps.

**Comment by velitasali** [comment]
@gvlfm78 Hi, sorry for late reply. I'm currently planning what to do for the next major release. I have also just started developing Windows application. So I added this to my to-do list. Thanks :)

**Comment by jerryn70** [comment]
@velitasali what about Windows Phone support ?

**Comment by velitasali** [comment]
@jerryn70 I am still getting used to the platform but if there will be support for windows phone, there won't be support windows 7, 8 that is for sure. Thanks.
