### ISSUE TITLE
Http Web Share feature

### ISSUE THREAD

**Issue by jerryn70** [genonbeta/TrebleShot#16]
It will be great if we have http Web Share feature.  Then we can share files to others, those who don't have trebleshot installed on their phones. This helps users to sent files to Windows Phone, IOS and PC also . 

You may think what feature is I'm telling about , so for more reference check this open source app called "share via http" https://github.com/marcosdiez/shareviahttp
Then you will get what feature iam telling about :grinning: 

If we implement this feature we can sent files to Windows phone and IOS . Trebleshot is not available for this 2 platforms so it's a great plus point. 

But what about receiving files from users those who don't have trebleshot installed on their phones or how Windows Phone and IOS users sent files to trebleshot user? Then I found this app called "fast file transfer" https://play.google.com/store/apps/details?id=com.floriandraschbacher.fastfiletransfer  this app has the ability to receive files from the users, whom don't have the same app installed on his phone.

**Comment by velitasali** [comment]
That kind of feature would clearly be something else as it would require me to do a lot of work and it would need to the same work for each plotform depending on the OS the user is running. So rather than this, developing platform specific apps is a faster process. Thanks :)

**Comment by jerryn70** [comment]
That's correct but this feature can reach more devices. Like If you not  developing windows 7,8 support apps

**Comment by velitasali** [comment]
@jerryn70 There will be support for Windows 7, 8 and I aggree with you that web share would be more generic platform in terms of usability but maintaining that seems to be harder.

**Comment by gvlfm78** [comment]
"it would need to the same work for each plotform depending on the OS the user is running."

I'm not exactly sure what you mean by this but an http server or even a simple webpage with a download  would work the same or almost the same across all platforms and browsers, without need for platform-specific code.

**Comment by velitasali** [comment]
I'm thinking of working on this.

**Comment by gvlfm78** [comment]
Hey @velitasali you're doing a great job with this app and have added many useful features that were suggested. I do not know if you have plans on making a Windows/Mac/Linux client to connect with the app, however a simple HTTP server which can be accessed from any browser would work great and relieve you of having to write platform-specific clients, and would cause me to make the definitive switch to this app nuking all of the similar ones off of my phone.

**Comment by SanmayJoshi** [comment]
+1 as this allows to send files to those not having trebleshot installed on android, or to pc.

**Comment by DeastinY** [comment]
any updates?

**Comment by velitasali** [comment]
@DeastinY Not working on this. The desktop version version uses Qt5 framework and may ease the development for iOS.

**Comment by DeastinY** [comment]
Alright, thanks for the fast response!
Desktop Version sounds amazing! I'll have a look at that :3

**Comment by velitasali** [comment]
This feature will be present with the version 1.4.0
