### ISSUE TITLE
Session started notification upon connecting to WiFi

### ISSUE THREAD

**Issue by gvlfm78** [genonbeta/TrebleShot#17]
After the latest update (at least the one on Google Play), whenever I connect to a WiFi network I get a notification from TrebleShot saying "TrebleShot can share files now: Tap to end session". This happens even when TrebleShot is not being used at all. Auto-start and scan devices automatically settings are disabled.

**Comment by velitasali** [comment]
Hi, can you tell what on what occasions it occurs? And could you please try first enabling and then disabling those settings you mentioned, and tell me the results? Thanks.

**Comment by gvlfm78** [comment]
After enabling and disabling again the "auto-start" option this no longer happens. It seems that with the update the setting was for some reason true even if it did not look like so in the app.

On a different device, installing it for the first time with the new version, the same problem occurs: i.e. even though "auto-start" is disabled the app acts like it is enabled, until it is turned on and off again.

**Comment by velitasali** [comment]
Yeah, I know why it occurs. Sorry about the issue, I will release a new version today.

**Comment by gvlfm78** [comment]
Great. Thanks for your work.
