### ISSUE TITLE
Replace 'refresh' icon with 'Search' icon

### ISSUE THREAD

**Issue by jerryn70** [genonbeta/TrebleShot#19]
When we open the app it shows, to find nearby devices click search button. but the button you provided is refresh button. 

Here is the search button icon 
![](https://i.imgur.com/Uvb8U4f.png)

**Comment by velitasali** [comment]
I don't think this icon is suitable for that kind of action.

**Comment by jerryn70** [comment]
Then we can change the search button text to refresh

**Comment by velitasali** [comment]
I don't understand why you think that way because even google itself uses that icon as an indicator of refreshing. 
![inkedscreenshot_20171210-140717_li](https://user-images.githubusercontent.com/10258162/33804344-cd254fb6-ddb3-11e7-8560-cf65a4f72a29.jpg)

**Comment by jerryn70** [comment]
@velitasli in the text you wrote 'Search' button but you provided a refresh icon . ![](https://i.imgur.com/W48fU8o.png)

**Comment by velitasali** [comment]
![screenshot_20180209-122800](https://user-images.githubusercontent.com/10258162/36020759-c568e664-0d94-11e8-919b-a15f35fa739c.png)
@jerryn70 The new version will include this UI. Though it may not be permanent.
