### ISSUE TITLE
Custom storage location does not work.

### ISSUE THREAD

**Issue by gerroon** [genonbeta/TrebleShot#2]
HI

I set "/storage/emulated/0/download/ to be the download location. And it does not seem like it is using that location it defaults to the Treble folder. 

I tried it on one lollipop and one nougat device.

thanks

**Comment by velitasali** [comment]
Hello :) Sorry about the issue. I think removing slash "/" at the end of the path will fix problem. Setting path is one of the earliest of features of TrebleShot, an GUI for it will probably be added on the next release. Thank you for your feedback :)
