### ISSUE TITLE
Can't make extsdcard as target path.

### ISSUE THREAD

**Issue by mobihack** [genonbeta/TrebleShot#22]
Can't make a folder in extsdcard as the path for receiving files :(
I'm liking everything so far. Good work dev :)

**Comment by velitasali** [comment]
Hey @mobihack,

Sorry about the problem. I am aware of it but as the release of version 1.2.5 took longer I expected, I had to leave it for the next release. I will be working on it. Thanks :)

**Comment by sixgeek** [comment]
Same for me. A really neat piece of software, beside the external storage topic. Please keep going and I'm looking forward for the integration.

**Comment by velitasali** [comment]
@sixgeek it should be working. Could you give more details like Android version and which folder you are trying to choose?

If you are running on Android 6+, you should follow these steps "File explorer > Mount directory > "choose SD card"

**Comment by sixgeek** [comment]
I'm running

Sender phone
LG G4 | LG-815 | LineageOS 14.1 | Android 7.1.2

Receiving phone
Samsung Galaxy S9+ | SM-G965F | Stock Rom | Android 8.0.0


I mounted already a folder (from external storage) on my receiver phone.

If I want to receive files or a folder, and if I just accept it, the files or the folder will arrive on my internal storage. No problem at all.

If the notification message arrived, that LG wants to send something I just passed the notification, then the app opens,
then I select on the receiving phone, save as,
then I select the mounted folder on the external storage, then the mounted folder opens inside of the app, 
then I select the check-mark sign (below on the right),
then the app and for checking of the files, I accept it,
then I get the message (bottom of the app with black background) something like transfer completed,
then I'll also receive a success notification on the status bar: task completed

However, if I go to the standard folder (internal storage) or the mounted folder (external storage), nothing has been received.

Did I do something wrong?

**Comment by velitasali** [comment]
@sixgeek I am sorry forthe inconvenince. The UX is a bit confusing I know, so there is nothing wrong actually. At the bottom you should have seen that "the folder has been set up as the target" or something like that. Afterwards as the last step, you need to tap the resume button or you can expand the notification to do so. 

![screenshot_20180530-221340](https://user-images.githubusercontent.com/10258162/40742520-7056fbd8-6457-11e8-9fd5-628e12c65ee7.png)
![inkedscreenshot_20180530-221320_li](https://user-images.githubusercontent.com/10258162/40742522-708cb688-6457-11e8-9522-8896b0f253ca.jpg)

**Comment by sixgeek** [comment]
No need to apologise. Thanks for the explanation! I understood what you wanted to say. Maybe it's helping to add a smaller text line below the "Save to" which shows the path.

It works and the topic can be closed. At least my own topic. Thanks for your support. Is there a possibility to through some coins into your hat?

I like the software and I'd like to see it in the future.

**Comment by velitasali** [comment]
This issue has a solution in here #62
