### ISSUE TITLE
1.2.5.2 crashes unless telephone permission is granted prior launch.

### ISSUE THREAD

**Issue by kulmegil** [genonbeta/TrebleShot#25]
Latest build crashes on clean install unless Telephone permission is granted prior launch.
Version 1.2.5.2

OnePlus 3T
stock rom, android 8.0 based

**Comment by velitasali** [comment]
@kulmegil , I couldn't understand how exactly it occurs. Do you mean the app crashes if you don't give telephone permission manually? If so, I am using emulator to test it on Oreo and I would appreciate if you could provide more information because I am not getting any error on emulator. Thanks.

**Comment by kulmegil** [comment]
Yes. 
On start it will asking for each permission, but immediately crashes before I can even click a button.

log:
[20180124_091425.zip](https://github.com/genonbeta/TrebleShot/files/1661531/20180124_091425.zip)

![screenshot_20180124-211949](https://user-images.githubusercontent.com/570575/35355095-86279440-014c-11e8-8bd9-80c80b0b8975.jpg)

**Comment by velitasali** [comment]
@kulmegil thank you for your help. I found the bug causing it https://github.com/genonbeta/TrebleShot/releases/tag/1.2.5.3

**Comment by kulmegil** [comment]
@velitasali working fine now.
