### ISSUE TITLE
Not showing phone memory in file explorer

### ISSUE THREAD

**Issue by jerryn70** [genonbeta/TrebleShot#27]
I tried to select some files that are on my phone memory using the file explorer option , but there is no  folder of my phone memory in it .

**Comment by velitasali** [comment]
@jerryn70 It should appear as "Emulated (0)". The new version will look like this. 
![screenshot_20180209-123504](https://user-images.githubusercontent.com/10258162/36021057-af87b2d4-0d95-11e8-8aa5-b050dd9f1870.png)

**Comment by jerryn70** [comment]
New version released. This issue can be closed.
