### ISSUE TITLE
File Explorer Default Path Set to Home

### ISSUE THREAD

**Issue by jerryn70** [genonbeta/TrebleShot#28]
Currently the default path when we open file explorer is STORAGE > EMULATED > 0 > TREBLESHOT 

Instead of that path , change it to HOME (the page in the below screenshot).

When we open file explorer it should display like the below screenshot
![](https://i.imgur.com/E9RQNsC.png)

So that we can easily go to sd card or phone memory or trebleshot folder.  Otherwise people with less knowledge will get confuse . Maybe they will feel difficulty in finding sd card or phone memory folders.

**Comment by velitasali** [comment]
@jerryn70 I think I can add an option for it.
