### ISSUE TITLE
Device name - max length only 14 chars?

### ISSUE THREAD

**Issue by kulmegil** [genonbeta/TrebleShot#29]
I would like to name my device something like "Kulmegil-OnePlus3T" but cannot since only 14 chars are allowed. Why such harsh name length restriction?

**Comment by velitasali** [comment]
@kulmegil thank you. I will try to find a way around. The reason was the hotspot name can only be 32 char, considering that, I thought I might other stuff to name area to improve information handling before network is connected.

**Comment by kwhitefoot** [comment]
The device name should really be of arbitrary length.  Then one would be able to use the same name as is used elsewhere.  For instance my phone's Bluetooth id is Sally Von Humpeding but that is much too long for TrebleShot.  Looks good otherwise!

**Comment by velitasali** [comment]
@kwhitefoot maximum length is now 32 chars. Is it enough?

**Comment by kwhitefoot** [comment]
In this case, yes.  But why have a limit at all?

**Comment by velitasali** [comment]
@kwhitefoot because otherwise it might get trimmed due to the limitions like max lenght of a hotspot name can be 32 chars
