### ISSUE TITLE
FR: Auto accept files

### ISSUE THREAD

**Issue by gerroon** [genonbeta/TrebleShot#3]
Hi

It would be great if the devices set to be auto accept files from the devices in the list. It is easy to miss the tray notification and it can get tedious when sharing many things.

thanks

**Comment by velitasali** [comment]
Hello :) I will consider adding it. Thank you for your feedback :)

**Comment by velitasali** [comment]
Hi, 

With the version 1.2.5.beta1 you can enable TrustZone to start file transfers without getting prompted. After giving permission permission a device to use TrustZone, enable TrustZone from the notification tray.

![screenshot_20180102-142804](https://user-images.githubusercontent.com/10258162/34482472-4dc2a2c8-efc9-11e7-8bba-b57483aed371.png)
![screenshot_20180102-142810](https://user-images.githubusercontent.com/10258162/34482473-4de24650-efc9-11e7-926d-062e52bdc294.png)

**Comment by ildar** [comment]
Great! waiting to see it in F-Droid (when you tag it)!

**Comment by ildar** [comment]
Just tested.
Sorry, this is cryptic:
TrustZone / Set Trust Zone default enabled when app starts.
Huh? I still don't understand that. 🙁

**Comment by ildar** [comment]
Ah! Got it.
May I suggest: "Enable TrustZone on this device on startup" ?
But actually I don't like the whole term of "TrustZone". Zone usually means
an area, but here we have a list. Feels different.
Emm, "White list" ?

**Comment by ildar** [comment]
Also it's a good idea to toast a message when user taps "Set as Trust Zone
device".
The message would tell "Files from this peer will be ACCEPTED without
prompt!"

**Comment by velitasali** [comment]
@ildar But the problem with calling it "white list"  is the list is also somehow a while list. The devices appear in there is there as they are considered trustful. That's why I went with "trustzone". The toast, by the way, would be useful. Thanks for the suggestions. I'm about to release a new version 👍
