### ISSUE TITLE
Is Location service mandatory ?

### ISSUE THREAD

**Issue by jerryn70** [genonbeta/TrebleShot#31]
Other apps like Shareit send anywhere doesn't require location to work . Why trebleshot needs location ?

**Comment by gvlfm78** [comment]
This is to create/see hotspots made by the app

**Comment by velitasali** [comment]
@jerryn70 it is needed to fetch network results on Android 6+ devices. Yes it is partly true what @gvlfm78 said. But you don't have to give permission for that. You can manually connect to the network. After the device connected, it will appear in the device list. But to create hotpots writing system setting permission is needed.
