### ISSUE TITLE
Bug found while sharing an image on Trebleshot. 

### ISSUE THREAD

**Issue by syedubair** [genonbeta/TrebleShot#33]
#### Expected behavior
App should be able to share images on instagram direct just as it shares them on other platforms like whatsapp. 

#### Actual behavior
We are not able to share an image through Instagram direct as it shows some unknown error occurred. 

#### How to reproduce
Launch the app. 
Press the options menu. 
Now click on images. 
Select an image by long pressing it. 
Now click on the share button and try to share via Instagram direct. 
A message will pop up saying an unknown error occurred. 

* App: TrebleShot-FileShare v1.2.5.6
* Operating system: Android Nought. 
Moto g5 plus

#### Recording Of The Bug
![20180218_003312.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518894545/dnkjk9hwjxhmrwxzwcy6.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/bug-found-while-sharing-an-image-on-trebleshot">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment]
Thanks for your feedback. It turns out the mime-type issue which now appears to be fixed. I will release a new version

**Comment by syedubair** [comment]
That will be great then

**Comment by velitasali** [comment]
@syedubair It is fixed in the new release.
