### ISSUE TITLE
share button does not work.

### ISSUE THREAD

**Issue by shirou-jeff** [genonbeta/TrebleShot#34]
#### Expected behavior
The user can share the application directly through other messaging media.

#### Actual behavior
The user cannot share the application directly through other messaging media because it is shared as a non-device-readable file.

#### How to reproduce
It is an application skill to be able to share them directly from the mobile device, but this is not the case with Trebleshot. Since when trying to share the application with other contacts, instead of sharing the link of the direct download for the application, this is received as a file not readable by the mobile device. In the video below, he provided evidence of how it looks, and how it should look when sharing a sample application.

* Browser: Trebleshot V 1.2.5.7
* Operating system: android 5.1.1

#### Recording Of The Bug
https://youtu.be/nM6SRVYBiuE

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/share-button-does-not-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment]
@shirou-jeff Actually that behaviour was what it was expected to do, however, it is also a good idea to let users choose how they want to share. I will try to add option for sharing play store link and other sources too. Thanks.

**Comment by gvlfm78** [comment]
Is it not supposed to send the apk file?

**Comment by EmmanuelMess** [comment]
@gvlfm78 Maybe wpp is breaking the openability?

**Comment by gvlfm78** [comment]
@EmmanuelMess I think even when sending the APK via Bluetooth it wasn't working.
