### ISSUE TITLE
Not able to share text through Instagram direct. 

### ISSUE THREAD

**Issue by syedubair** [genonbeta/TrebleShot#35]
#### Expected behavior
It is expected that the app should share text through Instagram like it shares on other networks like Gmail, whatsapp, sms, etc

#### Actual behavior
While trying to share text through Instagram direct the app couldn't share the text and everytime popped up a message saying an unknown error occurred. 

#### How to reproduce
1. Open the app and press the options button at top left. 
2. Click on Text Stream. 
3. Write some text here and press the share button to share the text you have written. 
4. Choose instagram direct option to share with a friend. 
5. Can't share any text as an error occurs. 

* App: Trebleshot v1.2.5.7 on Google play it shows v1.2.5.8
* Operating system: Android Nought (7.0) Moto g5 plus 

#### Recording Of The Bug
https://youtu.be/Xl1NC5HOGN8

  
[![Get_it_on_F-Droid.svg.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520145927/dtcqj0bdlh6qcjqzsdvp.png)
](https://f-droid.org/app/com.genonbeta.TrebleShot) 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/not-able-to-share-text-through-instagram-direct">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment]
Hi @syedubair 
 
Apparently you haven't tested it on the latest release. If you are using F-Droid as update channel, could you give feedback when the update is available on there, if not please let us know if the issue is still present.

Thanks.
