### ISSUE TITLE
[CRASH] TS needs permissions granted manually before start

### ISSUE THREAD

**Issue by ildar** [genonbeta/TrebleShot#39]
Clean data, AOSP 6.
TS crashes until Storage and Location permissions are granted manually.
[adb.logcat.log](https://github.com/genonbeta/TrebleShot/files/1801440/adb.logcat.log)
I know this doesn't happen on another Android 6 (CM-based).
Would you please look at it?

**Comment by velitasali** [comment]
@ildar normally I would expect there should have been a SecurityException thrown which apparently does not exist in the log file. What do you use to gather logs?

**Comment by ildar** [comment]
You're right. That logcat was captured by non-privileged user. Here comes
the fixed one.

**Comment by velitasali** [comment]
@ildar thanks, 

Could you give it a try? You **don't** have to uninstall release version. 
[app-debug.zip](https://github.com/genonbeta/TrebleShot/files/1808302/app-debug.zip)

**Comment by ildar** [comment]
Dear Veli Tasalı,
thank you so much for your support.
The debug apk doesn't crash yet politely asks for permissions.

**Comment by velitasali** [comment]
@ildar thank you
