### ISSUE TITLE
Please Add An Option To Change File Preview Style

### ISSUE THREAD

**Issue by IamJithendra** [genonbeta/TrebleShot#41]
Add An Option to Change The Files live Video ,Image Preview to Grid Or List Which Is Like

Or Change Video Preview Style To List Because It Now Unable to View the Full File Name

**Comment by velitasali** [comment]
@IamJithendra Thank you. It is on my to-do list already. With the next major release, something better will hopefully be present.

**Comment by velitasali** [comment]
Hi @IamJithendra ,

The latest release **1.2.6** features the grid view and changing preview style.

Thanks.
