### ISSUE TITLE
Data sent to developer

### ISSUE THREAD

**Issue by noyyalan** [genonbeta/TrebleShot#42]
after first install the app sends packets to the developer. May we know what info does it send?

**Comment by velitasali** [comment]
Hi @noyyalan ,

TrebleShot occasionally checks new version when the user starts the app. The request does not include any POST argument but just GET args, which means if you monitor the data which is sent and received you will see that the request routes this address;

https://api.github.com/repos/genonbeta/TrebleShot/releases defined in https://github.com/genonbeta/TrebleShot/blob/master/app/src/main/java/com/genonbeta/TrebleShot/config/AppConfig.java on line 19

As you might know, it is a way of gathering the releases on GitHub which is again provided by GitHub. So in conlusion there is no way I could collect any of users data in some or another using this.

This is an open source application, which means you can compile your own APK at any time or you can use F-Droid channel which compiles and releases the app using this repository. However, I can assure you this application does not collect any of your data, which you can confirm just by checking the source code.

If you have any further questions, please let me know.

**Comment by noyyalan** [comment]
Hi velitasali ,

Thank you for the reply and clarification. I am kiddo in app development and just was curious to know about the app communicating to GITHUB server.
I had raised this issue thinking that app is sending data to developer in background.

Thanks again for the clarification.

**Comment by velitasali** [comment]
@noyyalan I am glad you have asked about this and thank you.
