### ISSUE TITLE
One to many transfers

### ISSUE THREAD

**Issue by mahesh1729** [genonbeta/TrebleShot#43]
is it feasible to add a "send to many" option where more than one device can be connected to sender and all receive file simultaneously?

**Comment by velitasali** [comment]
@mahesh1729 

Thank you. It was already on my to-do list.

**Comment by velitasali** [comment]
Hi @mahesh1729 ,

The version **1.2.6** now supports adding more receivers to a pending transfer. 

Thanks.

**Comment by adbenitez** [comment]
still isn't enough :( it would be useful if we could check several devices before sharing the files

**Comment by velitasali** [comment]
> still isn't enough :( it would be useful if we could check several devices before sharing the files

Ensuring those devices are accessible would be a problem. New version will include the section shown below. It is more reliant, however, there is always a chance your suggestion might find way into the next releases, still not for the next release which is 1.2.8 (it have already taken a long time). Maybe for 1.2.8.1. 

![screenshot_1542658556](https://user-images.githubusercontent.com/10258162/48732568-1c884980-ec51-11e8-9a86-1728cedfca3e.png)
