### ISSUE TITLE
TrebleShot is not able to share text on text stream option via messenger lite on Android 7.0

### ISSUE THREAD

**Issue by NadiaMalik14** [genonbeta/TrebleShot#47]
#### Expected behavior
The app is expected to share the text written on text stream option of the app through messenger lite as it shares on other applications like Instagram direct and whatsapp. 

#### Actual behavior
The app is not able to share text in stream text option of the app via messenger lite. While selecting the messenger lite option the app selects the Facebook messenger lite and then gets back to the stream text option without sharing the text. 

#### How to reproduce
1. Launch the app. 
2. Go to options menu. 
3. Select text stream option and writes something. 
4. Select the share option on the top right corner of the screen. 
5. Select the messenger lite app to share the written text. 
6. Error occurs, the text isn't shared through messenger lite. 

* App: TrebleShot v1.2.5.12
* Operating system: Android Nought 7.0
* Device: Motorola Moto g5 plus
#### Recording Of The Bug
![20180403_094233.gif](https://cdn.utopian.io/posts/072adb957e298ba7af191b195472a8f9aaf620180403_094233.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@nadiamalik/trebleshot-is-not-able-to-share-text-on-text-stream-option-via-messenger-lite-on-android-7-0">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by velitasali** [comment]
Hey thank you for addressing the issue. TrebleShot uses a generic type of code to share a text and I think it depends on the developers of the app you mentioned. However, I will try to do something if possible.
