### ISSUE TITLE
i18n: needs more plurals

### ISSUE THREAD

**Issue by antonv6** [genonbeta/TrebleShot#5]
Android developer's guide suggests using [plurals](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) for "quantity strings" to make UI that looks and feels good in all languages.

Some of the strings in project's UI count something, like files or connections. Here are some that I've found:

```xml
<string name="multi_transfer_que">Receive %s file(s)?</string>
<string name="multiple_receive_done_summary">%s files received</string>
<string name="delete_warning">Do you want to delete %d file(s)</string>
<string name="delete_completed">%d file(s) is deleted</string>
<string name="file_count">%d file(s)</string>
<string name="dialog_msg_remove_queue_job">%d pending transfer(s) will be removed</string>
<string name="available_connections">%d connections</string>
```

To follow the guide, they need to be changed (at least some of them). For example, the first string would need to look like this:
```xml
<plurals name="multi_transfer_que">
    <item quantity="one">Receive %s file?</item>
    <item quantity="other">Receive %s files?</item>
</plurals>
```

The second string is only ever used for >1 files though, so it doesn't need to be changed, right? But it does! Many languages have non-trivial rules concerning plurals where correct spelling depends on the actual number (there are some examples in the quantity keyword table in the guide linked above). So this string also needs to be converted into `<plurals />` element and to include "one" and "other", even though it's used only for multiple files, otherwise it wouldn't look right in some languages.

This project is almost ready to receive translations, but not using plurals is something that can really prevent these translations from being complete.

**Comment by velitasali** [comment]
Thank you for letting me know this kind of feature is present. I'll make the changes and commit them today :)

**Comment by velitasali** [comment]
I updated language resources and removed old strings. I think it's ready to go.
