### ISSUE TITLE
Alternative themes.

### ISSUE THREAD

**Issue by killoid** [genonbeta/TrebleShot#6]
hi,
it would be great to have a dark mode & pure black amoled mode because too much white depletes more battery on my device because of the amoled screen.

**Comment by velitasali** [comment]
I'm adding this this to my to do list. it will possibly be featured in the next release. Thank you :)

**Comment by DMSalesman** [comment]
@velitasali Forgive me if I ask, but is this feature still in the works?

**Comment by velitasali** [comment]
I will be working on it in two days or so after the fix version is released for 12.4. Possibly, you'll be able to use it when the version 1.2.5 is released.

You can check the process in here
https://trello.com/b/YmbwDHHo/trebleshot-development
