### ISSUE TITLE
Add changelog link on F-Droid

### ISSUE THREAD

**Issue by pataquets** [genonbeta/TrebleShot#61]
There is a changelog file in the repo, but no changelog link appears on the F-Droid app. Had to dig the Gh repo to read it, no big deal. But will ease it to non technical users.
Filling some field or adding it to some manifest would do.
Thanks for such a useful app!

**Comment by velitasali** [comment]
I have added this to my to-do list. 

It will be gathering change-log over GitHub ( 
here https://github.com/genonbeta/TrebleShot/releases )

**Comment by pataquets** [comment]
Great! Thanks.

**Comment by velitasali** [comment]
@pataquets Starting with this commit F-Droid will show you what has changed. This change will include 1.2.7.2 and from 1.2.7.1 you are able to see changelog inside the app (see 'About'). And you will see a dialog whenever you update the app to a new version.
 
https://github.com/genonbeta/TrebleShot/commit/a478ad0742b1d49ff66baa376c38a62196bd69f8

**Comment by pataquets** [comment]
Great! That will help for sure, thanks. Checked it.
I understand you're keeping this open until the link to the full changelog is present in the app links section on F-Droid.

**Comment by pataquets** [comment]
I can see the changes in the app description details, very helpful, indeed.
What I also meant is a link to the full changelog URL in the bottom 'links' section of the app screen. It's the same section of the license, source and issue links.

**Comment by velitasali** [comment]
Thanks for reminding

**Comment by velitasali** [comment]
The link for changelog on F-Droid was added.

https://gitlab.com/fdroid/fdroiddata/blob/a548c9c2a86c6ffa5121639d62cdd08cec19ef2b/metadata/com.genonbeta.TrebleShot.yml#L8
