### ISSUE TITLE
[Solved] Setting "Storage path" to SD

### ISSUE THREAD

**Issue by ElTopo** [genonbeta/TrebleShot#62]
Hello,

As of version 1.2.7.2 stable release, it seems that I still can't set "Storage path" to a folder on SD card (from Preferences). It obviously that TrebleShot can read SD but I am not sure if it can write to SD. 

When I tried to change the storage path to a folder on SD card, I got "This folder cannot be used" (see the screenshot). Maybe this was because I didn't grant TrebleShot proper permissions, if so, what/how should I do?

![photo_2018-09-23_13-24-27](https://user-images.githubusercontent.com/217195/45932672-ac9d6180-bf34-11e8-9c76-31db8897d456.jpg)

Thanks.

**Comment by velitasali** [comment]
Sorry for inconvenience. Android 5+ requires explicit permission to access external storage and devices;

You can follow these steps;

*Tap "Mount folder" option*

![screenshot_20180924-000059_1](https://user-images.githubusercontent.com/10258162/45933038-82788d80-bf8e-11e8-882a-7e50d3d90dbe.jpg)

*Choose SD card or any other folder that you want to access*

![screenshot_20180924-000109_1](https://user-images.githubusercontent.com/10258162/45933018-55c47600-bf8e-11e8-909f-5345c68e953d.jpg)

*Select it*

![screenshot_20180924-000119](https://user-images.githubusercontent.com/10258162/45933019-55c47600-bf8e-11e8-8078-c27e2450621f.png)

*The folder is mounted and we have permission to access it. Go to "Home" by pressing back button or selecting it*

![screenshot_20180924-000134](https://user-images.githubusercontent.com/10258162/45933020-55c47600-bf8e-11e8-9429-9a988ae263b8.png)

*Now select it*

![screenshot_20180924-000416](https://user-images.githubusercontent.com/10258162/45933021-565d0c80-bf8e-11e8-8225-5bebac32f55a.png)

That should be it. Please let me know if something goes wrong,

Thanks.

**Comment by ElTopo** [comment]
@velitasali Thanks for the reply, finally I understand the meaning of "Mount folder".

I tried on several android devices (with SD), and now they work!

Thanks again!
