### ISSUE TITLE
pending even if the transfer is completed

### ISSUE THREAD

**Issue by Sopor** [genonbeta/TrebleShot#65]
**Describe the bug**
When sending files they will be added to the `Pending transfers` and i can see below the file pending. When the file is finished it quickly change from `pending` to `task complete` and then it change quickly back to `pending` again.
This happens only on the device that is sending. The receiving device will get 1/1 and `task complete`.

**To Reproduce**
Send a file from the `File explorer`

**Expected behavior**
It should change to `transfer complete` or something and not `pending`.

**Screenshots**
This is how it looks after the transfer is completed
![image](https://user-images.githubusercontent.com/5789283/46909553-ef02fe80-cf34-11e8-8b04-c4e1c39b4966.png)

**Environment (please complete the following information):**
 - Android version: Oreo 8.0
 - Language: English
 - App version 1.2.7.6
 - Device Model and Brand: Samsung Galaxy S9+(DevBase 5.9)

**Additional context**
Btw, you have a space between the ** and the char in
`** Environment (please complete the following information):**` and that will make the Markdown not work as it should.

**Comment by velitasali** [comment]
Thanks, it will be improved. It is not a bug actually, it works that way so when one wants to send same files to someone else, he/she can use *Add devices* option without mixing files sent and pending.
