### ISSUE TITLE
Hebrew should also have RTL support

### ISSUE THREAD

**Issue by yarons** [genonbeta/TrebleShot#67]
I recently translated TrebleShot to Hebrew using Weblate.

Sooner or later the Hebrew translation will be added to GitHub as well.

I've seen that Arabic already has RTL support and it looks pretty nice.

I wanted to know when will the Hebrew version will be merged and if it's possible to apply RTL to it as well.

BTW I've used this app and it's amazing, thank you so much for your excellent work!

**Comment by velitasali** [comment]
Amazing job thank you :+1:  I was trying to see how it works, however, even though Hebrew is applied system wide, it does not seem to effect the app. I have tried it by changing the internal language configuration within app, so it should have worked in any case whether it is applied system wide or not, still I could only be able to get it working with Android 4.1.2. 

![screenshot_1540034581](https://user-images.githubusercontent.com/10258162/47255296-71c91380-d477-11e8-857c-5f1c9da18e5a.png)

![screenshot_1540034618](https://user-images.githubusercontent.com/10258162/47255300-8b6a5b00-d477-11e8-896e-72aadeac4dd6.png)

**Comment by velitasali** [comment]
BTW I have merged your changes in "dev" branch. You can build from there or you can use this apk [app-fossReliant-release.zip](https://github.com/genonbeta/TrebleShot/files/2498091/app-fossReliant-release.zip)

**Comment by yarons** [comment]
Oh yeah, I know this one.

Hebrew is usually denoted by the alias "he", for some reason, in Android it's "iw".

Changing values-he to values-iw fixes this problem, it's also possible to create a symlink between them (might break dev environment for Windows developers).

**Comment by velitasali** [comment]
@yarons I can add a build command to add Hebrew related resources to build folder, but I need to know if it is not possible to just use "iw" or some Android versions or variants just don't use it as well. What do you think?

**Comment by yarons** [comment]
I know they fixed it but it's still backwards compatible, so 6 onward is using also `he` if I'm not mistaken.

**Comment by yarons** [comment]
Oh yeah! You seem like you know your stuff very well! Way to go! I'm super proud, thank you so much!

**Comment by velitasali** [comment]
Your welcome :+1:
