### ISSUE TITLE
Sharing Images

### ISSUE THREAD

**Issue by gabm** [genonbeta/TrebleShot#7]
I would like to share images primarily.. Do I overlook this option or is it currently not available?

Thanks a lot for this app, looks very promising!

**Comment by velitasali** [comment]
Sorry about the confusion. Image sharing in TrebleShot  is currently not available. I wanted it to have a proper UI for image sharing. Hope I can add it in the next releases. Thank you :)

**Comment by gabm** [comment]
cool, definately waiting for that... ;)

/offtopic: whenever you are ready with the language restructuring, I could contribute some languages.. please give me a pingback once its ready !

**Comment by velitasali** [comment]
I just completed doing it. It would be great by the way. Thank you :)

**Comment by jerryn70** [comment]
@velitasali add images, Archives, Documents etc option to here ![](https://i.imgur.com/nv8OQwS.jpg)

**Comment by velitasali** [comment]
@jerryn70 Image sharing within the app will be present in the future but I can't say exactly when and the other features you mentioned are a mystery . Thanks.
