### ISSUE TITLE
Turn on wifi inside app

### ISSUE THREAD

**Issue by adbenitez** [genonbeta/TrebleShot#71]
When I go to the "Connect" tab it shows "To connect to devices Wi-Fi should be turned on", it is a bit annoying to have to go out of the app to turn on wifi.

Can't the app turn on wifi automatically when we go to the tab "Connect"? or at least show a button "TURN ON WIFI" similar to the "SET UP HOTSPOT" button in the "Network" tab?

Best regards,
adb

**Comment by velitasali** [comment]
@adbenitez I am redesigning the app. Actually there have many changes. The permissions and other snack bar warnings will be reduced to cards constantly appearing on the screen when needed. This way of executing features would be more convenient hopefully.

**Comment by adbenitez** [comment]
This works in v1.2.8.1
