### ISSUE TITLE
[Feature Request] TrebleShot ID Generate

### ISSUE THREAD

**Issue by TsukihiAraragi** [genonbeta/TrebleShot#75]
1. Generate special ID without IMEI/MEID to avoid request Read Phone State Permission. 
2. Generated special ID no longer be constant, after resinstall TrebleShot, new special ID should be generated. 
3.  Import/Output/Regenerate special ID to xml or other format. 
:-)

**Comment by TsukihiAraragi** [comment]
@velitasali Is TrebleShot Desktop  generates unique ID with MAC Adreess? I think MAC Adresss is better than IMEI/MEID on moblie devices , and some tablet devices do not have any IMEI or MEID.

**Comment by velitasali** [comment]
> @velitasali Is TrebleShot Desktop generates unique ID with MAC Adreess? I think MAC Adresss is better than IMEI/MEID on moblie devices , and some tablet devices do not have any IMEI or MEID.

Gathering MAC address requires location to be enabled and ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION permission on Android 6/API23 and later.

Desktop version currently generates a random uuid. It may change though.

https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-hardware-id

**Comment by velitasali** [comment]
Version 2.0 will have this change.
