### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by Sopor-** [genonbeta/TrebleShot#76]
The [link](https://t.me/trebleshotLang) to join the translation community seems to not work from the [here](https://github.com/genonbeta/TrebleShot/wiki/Language-contribution)

**Comment by velitasali** [comment]
Hi @Sopor- ,

That is a Telegram link. You can open with Telegram or on a web browser. What issue are you having?

**Comment by Sopor-** [comment]
I believe i misunderstood it... I thought it should point me to the translation page and because i don't have the Telegram app this link won't work tg://resolve?domain=trebleshotLang, so i'm closing it.
Sorry to bother you  ...

**Comment by velitasali** [comment]
No problem. The direct link to the translation page is https://hosted.weblate.org/engage/TrebleShot . The community is for asking questions etc.
