### ISSUE TITLE
Add support for receiving from and sending to ShareIt clients

### ISSUE THREAD

**Issue by A-Shahbazi** [genonbeta/TrebleShot#77]
**Is your feature request related to a problem? Please describe.**
No.
The userbase for trebleshot is very low although it provides the exact same features as closed-source alternatives like ShareIt. So it can be a good idea to add support for sending to/receiving from ShareIt clients which will expand the app's interoperability and userbase.
BTW, it will be a smart strategy to expand the userbase because when encountered the user will prefer an open source app with the ability of interconnection with ShareIt users.

**Describe the solution you'd like**
Add support for sending to/receiving from ShareIt clients.

**Describe alternatives you've considered**

**Additional context**

**Comment by velitasali** [comment]
Hi @A-Shahbazi, I am currently working on the desktop version. This was previously discussed, but I could not find it. I will leave it here if I can find. I will return to this later. Thanks.

**Comment by contrapunctus-1** [comment]
Duplicate of https://github.com/genonbeta/TrebleShot/issues/30

**Comment by A-Shahbazi** [comment]
Whoops! Then I'm closing this because it's a duplicate.
Sorry!
