### ISSUE TITLE
Is "modify system settings" really necessary?

### ISSUE THREAD

**Issue by floppyD** [genonbeta/TrebleShot#80]
I've been wondering if that permission is really necessary, since another wifi based file transfer app I use (SuperBeam) doesn't need it, it doesn't even need to create a hotspot (I dunno how it really works, but it doesn't show as hotspot and it doesn't disable wifi, only "suspend" it). I really want to use this app since it's FOSS, but this is bugging me, not only because it's a rather invasive permission, but because when you create a hotspot it disables your wifi, so you have to enable it again when you are done transferring your files. By the way, good job, the interface is really good.

**Comment by velitasali** [comment]
Below Android 8, it is required to start hotspot. However, there was no attempt to hide it for Android 8 and above. Adding this to my to-do list.

**Comment by floppyD** [comment]
Actually I'm on 7.1.2 and SuperBeam doesn't start a hotspot, I have a device on ICS at home and I'm pretty sure it doesn't need to start a hotspot too, I can check it out later. Not having to set a hotspot makes everything seamless, you just transfer you files and you are back to your network, no additional steps or additional permissions.
![Screenshot_20190326-160725](https://user-images.githubusercontent.com/29208110/55026381-a2dae080-4fe1-11e9-9c3f-458fd7761619.png)

**Comment by floppyD** [comment]
Same on 4.1.2, I dunno what kind of sorcery they are doing but it works lol
![Screenshot_2019-03-26-18-53-49](https://user-images.githubusercontent.com/29208110/55036281-e3922400-4ff8-11e9-9e1d-87c66e0ce902.png)

**Comment by no-name-yet-yet** [comment]
The technology used by superbeam is "wifi direct".

[WiFi-Direct, android developer](https://developer.android.com/training/connect-devices-wirelessly/wifi-direct)

**Comment by floppyD** [comment]
I always thought WiFi-Direct was simply a pretty name for transferring data been two devices wirelessly without needing an internet connection. Good to know it is a standard.

**Comment by velitasali** [comment]
I tested it today and it turns out that Writing System Settings permission is required with Oreo and later as well. So no change is possible at the moment.

For the status of Wi-Fi Direct: https://github.com/genonbeta/TrebleShot/issues/81
