### ISSUE TITLE
Download all option for http web share

### ISSUE THREAD

**Issue by exomar** [genonbeta/TrebleShot#86]
Great to see Http Web Share feature #16 in last update. Very useful and instantly adds compatibilty to almost all platforms.

One way to improve this feature further could be to add download all option when sharing multiple files(Sometimes can be 1000s). If easier to do may be zip to single file to make transfer.

Just a suggestion not a request. Since recently added may be already familiar territory. Appreciate all the cool stuff and attention to small details all around the app.

**Comment by velitasali** [comment]
Download all option is not my favorite. The second one, though, is good idea. I guess I can do that.
