### ISSUE TITLE
Allow receiving files in web interface

### ISSUE THREAD

**Issue by ByteHamster** [genonbeta/TrebleShot#87]
Usually, the people I am exchanging files with do not want to install an app just to send me a file. So in most cases, we fall back to the slow Bluetooth instead. The web server is a huge step into the right direction. To make the app fully work when installed on one single device, please add a feature to also receive files using the web interface. There could be an upload button in the web interface that allows others to send files to my device.

**Comment by velitasali** [comment]
Added this in to-do list.

**Comment by crone123** [comment]
Hello,
I discovered this app today, it's really a beautiful app, thank you !
I think the only really missing feature is this feature, it would be really nice if from the "sharing via browser" you can just upload, or drag and drop files from the desktop to the phone !
Thank you for making this great app !

**Comment by ByteHamster** [comment]
Wonderful! Thanks a lot. Version 1.4.2 now has the feature. :+1:

**Comment by mubashir-rehman** [comment]
#feature Reequest:
Add allow the upload button to send multiple files.
Currently only one file can be sent at a time.

**Comment by ByteHamster** [comment]
@mubashir-rehman Please open a new issue for that. This issue is already implemented, so your request will likely be forgotten if it is only posted here.
