### ISSUE TITLE
Version no longer supported issue - Eski versiyon hatası

### ISSUE THREAD

**Issue by 1emirozdemir** [genonbeta/TrebleShot#89]
Merhaba uygulamanın en son versiyonunu kullandığımız halde birbirimize dosya gönderirken bu cihaz artık desteklenmeyen eski sürüm kullanıyor hatası alıyoruz. bu modulü nasıl devre dışı bırakabiliriz teşekkürler. Geliştirmek için var gücümüzle çalışıyoruz.

**Comment by velitasali** [comment]
Merhaba ve teşekkürler, 
Öncelikle başlığa çevirisini eklediğimi belirteyim.

Sürümü güncelledikten sonra cihazı tekrar tanıtmanız gereklidir. Bunu cihazları aynı ağa bağladıktan sonra TrebleShot'u açarak veya "Bağlantıyı düzelt" gibi herhangi bir desteklenen yöntemle yapabilirsiniz.


[En]
A rescan is needed for devices to recognize that they have a newer version.
