### ISSUE TITLE
CursorWindow: Failed to read row 0, column -1

### ISSUE THREAD

**Issue by relan** [genonbeta/TrebleShot#9]
Every time I try to share a file via TrebleShot it crashes. I'm on Android 7.1.2.

Steps to reproduce (all on the same device):
1. Start TrebleShot 1.2.1 and add a remote device.
2. Download a file from Internet using a browser.
3. Open the Android's Downloads app.
4. Long press the file and tap Share.
5. Select TrebleShot in the sharing dialog. TrebleShot crashes.

Logcat:
```
05-30 22:04:18.062  5080  5100 E CursorWindow: Failed to read row 0, column -1 from a CursorWindow which has 1 rows, 6 columns.
05-30 22:04:18.063  5080  5100 E AndroidRuntime: FATAL EXCEPTION: Thread-2
05-30 22:04:18.063  5080  5100 E AndroidRuntime: Process: com.genonbeta.TrebleShot, PID: 5080
05-30 22:04:18.063  5080  5100 E AndroidRuntime: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at android.database.CursorWindow.nativeGetString(Native Method)
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at android.database.CursorWindow.getString(CursorWindow.java:438)
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at com.genonbeta.TrebleShot.helper.ApplicationHelper.getFileFromUri(ApplicationHelper.java:54)
05-30 22:04:18.063  5080  5100 E AndroidRuntime: 	at com.genonbeta.TrebleShot.activity.ShareActivity$4.run(ShareActivity.java:230)
```

The code assumes that each MediaStore entry has a DATA field:

            Cursor cursor = context.getContentResolver().query(fileUri, null, null, null, null);

            if (cursor != null)
            {
                if (cursor.moveToFirst())
                {
                    int dataIndex = cursor.getColumnIndex(MediaStore.MediaColumns.DATA);
                    String dataPath = cursor.getString(dataIndex);

                    file = new File(dataPath);
                }

                cursor.close();
            }

This is not the case on recent Android versions. In general, [you cannot convert](https://commonsware.com/blog/2016/03/15/how-consume-content-uri.html) a `content://` URI into a `file://` URI.

**Comment by velitasali** [comment]
Thank you for your feedback. I think I'm going to change the way trebleshot stores file path. Possibly keeping the uri rather than changing it to file path is a more stable way of handling them. But getting file size still remains as an issue.

**Comment by relan** [comment]
> But getting file size still remains as an issue.

You can get the [size from MediaStore](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns.html#SIZE).

**Comment by velitasali** [comment]
The issue was fixed in the new version.
