### ISSUE TITLE
Bottom bar

### ISSUE THREAD

**Issue by 1emirozdemir** [genonbeta/TrebleShot#92]
Merhaba uygulamanızın tasarımını kütüphane olarak kullanıyorum da acaba bottom bar'a yeni bir tane fragment nasıl ekleyebiliriz. 

Aktarımlar -- Dosya gezgini-- Mesaj -- Yeni bir fragment

Teşekkürler

**Comment by velitasali** [comment]
Merhaba,

Düzenlemeniz gereken HomeFragment sınıfıdır. 
https://github.com/genonbeta/TrebleShot/blob/fdb7d2d7fd5fd5f7b966a0e3cb2bfaeb3e481427/app/src/main/java/com/genonbeta/TrebleShot/fragment/HomeFragment.java#L38

Önceden yazdığım `SmartFragmentPagerAdapter` sınıfı, dinamik bir şekilde fragment yüklemesini gerçekleştirecektir.

```java
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState)
    {
        // ... diğer kodlar

        // Tüm 3 sınıf burada tanımlanmıştır
        mAdapter.add(new SmartFragmentPagerAdapter.StableItem(0, TransferGroupListFragment.class, null));
        mAdapter.add(new SmartFragmentPagerAdapter.StableItem(1, FileExplorerFragment.class, null));
        mAdapter.add(new SmartFragmentPagerAdapter.StableItem(2, TextStreamListFragment.class, null));
```

Sonraki fragment'ıda şu şekilde gözükecek şekilde belirtebilirsiniz:
`mAdapter.add(new SmartFragmentPagerAdapter.StableItem(3, SINIF_ADI.class, null));`

**Comment by 1emirozdemir** [comment]
Çok teşekkür ederim.

**Comment by 1emirozdemir** [comment]
Ama bahsettiğiniz kodları hem HomeActivity'dde hemde SmartFragmentPagerAdapter'de bulamadım
