### ISSUE TITLE
Turn on "share via browser" by default

### ISSUE THREAD

**Issue by chenyue404** [genonbeta/TrebleShot#94]
**Is your feature request related to a problem? Please describe.**
Usually, my friend didn't install the client. I want him to get the sharing directly through the browser, but I need to manually open it every time, it's very troublesome.

**Describe the solution you'd like**
Turn on "share via browser" by default. Or add an option in preferences.

**Comment by velitasali** [comment]
Hey, I should think about how this should be done. Making this change without precautions might be insecure.

**Comment by velitasali** [comment]
Version 2.0 will have this change.
