### ISSUE TITLE
Add received pictures to media scanner

### ISSUE THREAD

**Issue by ByteHamster** [genonbeta/TrebleShot#95]
**Is your feature request related to a problem? Please describe.**
When I receive a picture using the web interface (someone sends me the file by uploading), it does not appear in the phone's gallery. The file is visible in file managers. If I reboot my phone, it appears in the gallery. 

**Describe the solution you'd like**
Add all received files to the Android media scanner

**Comment by velitasali** [comment]
Hey, thanks for opening this. I forgot to do it.
